spring:
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/users_service
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
